### ISSUE TITLE
URL encoding problem (spaces in path)

### ISSUE THREAD

**Issue by dkocher** [lookfirst/sardine#120]
_Original author: kamil.to...@gmail.com (April 18, 2012 10:05:31)_

I didn't found way how to get content of directory which name contains spaces.

Example(1):
  sardine.getResources(&quot;https://dav.memopal.com/My Computers/&quot;);
Result(1):
  java.lang.IllegalArgumentException: Illegal character in path.

Example(2):
  sardine.getResources(&quot;https://dav.memopal.com/My%20Computers/&quot;);
Result(2):
  java.lang.StringIndexOutOfBoundsException: String index out of range: -2
  at com.googlecode.sardine.SardineImpl.getResources(SardineImpl.java:224)

I thing that problem could be solved in method SardineImpl.getResources(url). I don't know whether argument URL should be encoded or not. If yes, then comparing baseUrl should be on encoded URLs too (or both decoded). If no, then HttpPropFind constructor or executeWrapper should encode it.

regards
Kamil Tollinger

_Original issue: http://code.google.com/p/sardine/issues/detail?id=120_

**Comment by cuculala** [comment]
Sardine 5.8. The encoded URI with spaces is found to be illegel character.
Have you experienced this ?

encoded URI: **http://{hostname}/remote.php/webdav/My%20Folder4/**


java.net.URISyntaxException: Illegal character in path at index 54: http://{hostname}/remote.php/webdav/My Folder4/
        at java.net.URI$Parser.fail(URI.java:2848) ~[na:1.8.0_92]
        at java.net.URI$Parser.checkChars(URI.java:3021) ~[na:1.8.0_92]
        at java.net.URI$Parser.parseHierarchical(URI.java:3105) ~[na:1.8.0_92]
        at java.net.URI$Parser.parse(URI.java:3053) ~[na:1.8.0_92]
        at java.net.URI.<init>(URI.java:588) ~[na:1.8.0_92]
        at java.net.URI.create(URI.java:850) ~[na:1.8.0_92]
        at org.apache.http.client.methods.HttpHead.<init>(HttpHead.java:72) ~[httpclient-4.5.1.jar:4.5.1]
        at com.github.sardine.impl.SardineImpl.exists(SardineImpl.java:997) ~[sardine-5.8.jar:5.8]
