### ISSUE TITLE
Unable to put file on sharepoint webdav

### ISSUE THREAD

**Issue by chudzikp** [lookfirst/sardine#215]
Hi I'm trying to use sardine to upload files on sharepoint 2010 webdav.
Unfortunately it's not working ;(

Here is code I'm trying to use to upload file:
```
final Sardine sardine = SardineFactory.begin(login, pass);
sardine.put(fileUrl, is);
```

And here is error:
```
Exception in thread "main" org.apache.http.NoHttpResponseException: kauab-we3.collaboration.example.com:80 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:214)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160)
	at com.github.sardine.impl.SardineImpl.execute(SardineImpl.java:904)
	at com.github.sardine.impl.SardineImpl.put(SardineImpl.java:831)
	at com.github.sardine.impl.SardineImpl.put(SardineImpl.java:814)
	at com.github.sardine.impl.SardineImpl.put(SardineImpl.java:802)
	at com.github.sardine.impl.SardineImpl.put(SardineImpl.java:764)
	at com.github.sardine.impl.SardineImpl.put(SardineImpl.java:757)
	at com.github.sardine.impl.SardineImpl.put(SardineImpl.java:750)
	at com.github.sardine.impl.SardineImpl.put(SardineImpl.java:744)
	at sardine.SardineClient.uploadFile(SardineClient.java:77)
	at sardine.SardineClient.main(SardineClient.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

I've tried using expectContinue=false and setting content length but it's not working.
list and get works fine. delete is not working either, but one step at a time :)

And here is debug log:
```
INFO - 2015-07-06 14:59:56,053 - sardine.SardineClient - Started SardineClient in 1.745 seconds (JVM running for 4.168)
DEBUG - 2015-07-06 14:59:56,165 - org.apache.http.client.protocol.RequestAddCookies - CookieSpec selected: best-match
DEBUG - 2015-07-06 14:59:56,177 - org.apache.http.client.protocol.RequestAuthCache - Auth cache not set in the context
DEBUG - 2015-07-06 14:59:56,179 - org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection request: [route: {}->http://kauab-we3.collaboration.example.com:80][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
DEBUG - 2015-07-06 14:59:56,198 - org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {}->http://kauab-we3.collaboration.example.com:80][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
DEBUG - 2015-07-06 14:59:56,200 - org.apache.http.impl.execchain.MainClientExec - Opening connection {}->http://kauab-we3.collaboration.example.com:80
DEBUG - 2015-07-06 14:59:56,269 - org.apache.http.impl.conn.HttpClientConnectionOperator - Connecting to kauab-we3.collaboration.example.com/145.245.197.51:80
DEBUG - 2015-07-06 14:59:56,342 - org.apache.http.impl.conn.HttpClientConnectionOperator - Connection established 10.128.24.12:50826<->example.com.ip:80
DEBUG - 2015-07-06 14:59:56,342 - org.apache.http.impl.execchain.MainClientExec - Executing request PUT /team/5e66/Documents/test2.txt HTTP/1.1
DEBUG - 2015-07-06 14:59:56,342 - org.apache.http.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
DEBUG - 2015-07-06 14:59:56,343 - org.apache.http.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
DEBUG - 2015-07-06 14:59:56,345 - org.apache.http.headers - http-outgoing-0 >> PUT /team/5e66/Documents/test2.txt HTTP/1.1
DEBUG - 2015-07-06 14:59:56,346 - org.apache.http.headers - http-outgoing-0 >> Expect: 100-continue
DEBUG - 2015-07-06 14:59:56,346 - org.apache.http.headers - http-outgoing-0 >> Content-Type: ISO-8859-1
DEBUG - 2015-07-06 14:59:56,346 - org.apache.http.headers - http-outgoing-0 >> Transfer-Encoding: chunked
DEBUG - 2015-07-06 14:59:56,346 - org.apache.http.headers - http-outgoing-0 >> Host: kauab-we3.collaboration.example.com
DEBUG - 2015-07-06 14:59:56,346 - org.apache.http.headers - http-outgoing-0 >> Connection: Keep-Alive
DEBUG - 2015-07-06 14:59:56,346 - org.apache.http.headers - http-outgoing-0 >> User-Agent: Sardine/5.4
DEBUG - 2015-07-06 14:59:56,346 - org.apache.http.headers - http-outgoing-0 >> Accept-Encoding: gzip,deflate
DEBUG - 2015-07-06 14:59:56,346 - org.apache.http.wire - http-outgoing-0 >> "PUT /team/5e66/Documents/test2.txt HTTP/1.1[\r][\n]"
DEBUG - 2015-07-06 14:59:56,346 - org.apache.http.wire - http-outgoing-0 >> "Expect: 100-continue[\r][\n]"
DEBUG - 2015-07-06 14:59:56,346 - org.apache.http.wire - http-outgoing-0 >> "Content-Type: ISO-8859-1[\r][\n]"
DEBUG - 2015-07-06 14:59:56,346 - org.apache.http.wire - http-outgoing-0 >> "Transfer-Encoding: chunked[\r][\n]"
DEBUG - 2015-07-06 14:59:56,346 - org.apache.http.wire - http-outgoing-0 >> "Host: kauab-we3.collaboration.example.com[\r][\n]"
DEBUG - 2015-07-06 14:59:56,346 - org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
DEBUG - 2015-07-06 14:59:56,346 - org.apache.http.wire - http-outgoing-0 >> "User-Agent: Sardine/5.4[\r][\n]"
DEBUG - 2015-07-06 14:59:56,346 - org.apache.http.wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
DEBUG - 2015-07-06 14:59:56,346 - org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
DEBUG - 2015-07-06 14:59:56,451 - org.apache.http.wire - http-outgoing-0 << "HTTP/1.1 401 Unauthorized[\r][\n]"
DEBUG - 2015-07-06 14:59:56,451 - org.apache.http.wire - http-outgoing-0 << "Server: Microsoft-IIS/7.5[\r][\n]"
DEBUG - 2015-07-06 14:59:56,451 - org.apache.http.wire - http-outgoing-0 << "SPRequestGuid: 326377b3-3478-4611-a6ff-08dd74be58f1[\r][\n]"
DEBUG - 2015-07-06 14:59:56,452 - org.apache.http.wire - http-outgoing-0 << "WWW-Authenticate: NTLM[\r][\n]"
DEBUG - 2015-07-06 14:59:56,452 - org.apache.http.wire - http-outgoing-0 << "X-Powered-By: ASP.NET[\r][\n]"
DEBUG - 2015-07-06 14:59:56,452 - org.apache.http.wire - http-outgoing-0 << "SharePointServer: RKAMVSPAB01[\r][\n]"
DEBUG - 2015-07-06 14:59:56,452 - org.apache.http.wire - http-outgoing-0 << "MicrosoftSharePointTeamServices: 14.0.0.7113[\r][\n]"
DEBUG - 2015-07-06 14:59:56,452 - org.apache.http.wire - http-outgoing-0 << "X-MS-InvokeApp: 1; RequireReadOnly[\r][\n]"
DEBUG - 2015-07-06 14:59:56,452 - org.apache.http.wire - http-outgoing-0 << "Date: Mon, 06 Jul 2015 12:59:55 GMT[\r][\n]"
DEBUG - 2015-07-06 14:59:56,452 - org.apache.http.wire - http-outgoing-0 << "Content-Length: 0[\r][\n]"
DEBUG - 2015-07-06 14:59:56,452 - org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
DEBUG - 2015-07-06 14:59:56,457 - org.apache.http.headers - http-outgoing-0 << HTTP/1.1 401 Unauthorized
DEBUG - 2015-07-06 14:59:56,457 - org.apache.http.headers - http-outgoing-0 << Server: Microsoft-IIS/7.5
DEBUG - 2015-07-06 14:59:56,457 - org.apache.http.headers - http-outgoing-0 << SPRequestGuid: <cut>
DEBUG - 2015-07-06 14:59:56,457 - org.apache.http.headers - http-outgoing-0 << WWW-Authenticate: NTLM
DEBUG - 2015-07-06 14:59:56,457 - org.apache.http.headers - http-outgoing-0 << X-Powered-By: ASP.NET
DEBUG - 2015-07-06 14:59:56,457 - org.apache.http.headers - http-outgoing-0 << SharePointServer: RKAMVSPAB01
DEBUG - 2015-07-06 14:59:56,457 - org.apache.http.headers - http-outgoing-0 << MicrosoftSharePointTeamServices: 14.0.0.7113
DEBUG - 2015-07-06 14:59:56,457 - org.apache.http.headers - http-outgoing-0 << X-MS-InvokeApp: 1; RequireReadOnly
DEBUG - 2015-07-06 14:59:56,457 - org.apache.http.headers - http-outgoing-0 << Date: Mon, 06 Jul 2015 12:59:55 GMT
DEBUG - 2015-07-06 14:59:56,457 - org.apache.http.headers - http-outgoing-0 << Content-Length: 0
DEBUG - 2015-07-06 14:59:56,462 - org.apache.http.impl.execchain.MainClientExec - Connection can be kept alive indefinitely
DEBUG - 2015-07-06 14:59:56,463 - org.apache.http.impl.auth.HttpAuthenticator - Authentication required
DEBUG - 2015-07-06 14:59:56,463 - org.apache.http.impl.auth.HttpAuthenticator - kauab-we3.collaboration.example.com:80 requested authentication
DEBUG - 2015-07-06 14:59:56,463 - org.apache.http.impl.client.TargetAuthenticationStrategy - Authentication schemes in the order of preference: [negotiate, Kerberos, NTLM, Digest, Basic]
DEBUG - 2015-07-06 14:59:56,464 - org.apache.http.impl.client.TargetAuthenticationStrategy - Challenge for negotiate authentication scheme not available
DEBUG - 2015-07-06 14:59:56,464 - org.apache.http.impl.client.TargetAuthenticationStrategy - Challenge for Kerberos authentication scheme not available
DEBUG - 2015-07-06 14:59:56,470 - org.apache.http.impl.client.TargetAuthenticationStrategy - Challenge for Digest authentication scheme not available
DEBUG - 2015-07-06 14:59:56,471 - org.apache.http.impl.client.TargetAuthenticationStrategy - Challenge for Basic authentication scheme not available
DEBUG - 2015-07-06 14:59:56,471 - org.apache.http.impl.auth.HttpAuthenticator - Selected authentication options: [NTLM]
DEBUG - 2015-07-06 14:59:56,472 - org.apache.http.impl.execchain.MainClientExec - Executing request PUT /team/5e66/Documents/test2.txt HTTP/1.1
DEBUG - 2015-07-06 14:59:56,472 - org.apache.http.impl.execchain.MainClientExec - Target auth state: CHALLENGED
DEBUG - 2015-07-06 14:59:56,472 - org.apache.http.impl.auth.HttpAuthenticator - Generating response to an authentication challenge using ntlm scheme
DEBUG - 2015-07-06 14:59:56,486 - org.apache.http.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
DEBUG - 2015-07-06 14:59:56,486 - org.apache.http.headers - http-outgoing-0 >> PUT /team/5e66/Documents/test2.txt HTTP/1.1
DEBUG - 2015-07-06 14:59:56,486 - org.apache.http.headers - http-outgoing-0 >> Expect: 100-continue
DEBUG - 2015-07-06 14:59:56,486 - org.apache.http.headers - http-outgoing-0 >> Content-Type: ISO-8859-1
DEBUG - 2015-07-06 14:59:56,486 - org.apache.http.headers - http-outgoing-0 >> Transfer-Encoding: chunked
DEBUG - 2015-07-06 14:59:56,486 - org.apache.http.headers - http-outgoing-0 >> Host: kauab-we3.collaboration.example.com
DEBUG - 2015-07-06 14:59:56,486 - org.apache.http.headers - http-outgoing-0 >> Connection: Keep-Alive
DEBUG - 2015-07-06 14:59:56,486 - org.apache.http.headers - http-outgoing-0 >> User-Agent: Sardine/5.4
DEBUG - 2015-07-06 14:59:56,486 - org.apache.http.headers - http-outgoing-0 >> Accept-Encoding: gzip,deflate
DEBUG - 2015-07-06 14:59:56,486 - org.apache.http.headers - http-outgoing-0 >> Authorization: NTLM <cut>
DEBUG - 2015-07-06 14:59:56,486 - org.apache.http.wire - http-outgoing-0 >> "PUT /team/5e66/Documents/test2.txt HTTP/1.1[\r][\n]"
DEBUG - 2015-07-06 14:59:56,486 - org.apache.http.wire - http-outgoing-0 >> "Expect: 100-continue[\r][\n]"
DEBUG - 2015-07-06 14:59:56,486 - org.apache.http.wire - http-outgoing-0 >> "Content-Type: ISO-8859-1[\r][\n]"
DEBUG - 2015-07-06 14:59:56,486 - org.apache.http.wire - http-outgoing-0 >> "Transfer-Encoding: chunked[\r][\n]"
DEBUG - 2015-07-06 14:59:56,486 - org.apache.http.wire - http-outgoing-0 >> "Host: kauab-we3.collaboration.example.com[\r][\n]"
DEBUG - 2015-07-06 14:59:56,486 - org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
DEBUG - 2015-07-06 14:59:56,486 - org.apache.http.wire - http-outgoing-0 >> "User-Agent: Sardine/5.4[\r][\n]"
DEBUG - 2015-07-06 14:59:56,486 - org.apache.http.wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
DEBUG - 2015-07-06 14:59:56,486 - org.apache.http.wire - http-outgoing-0 >> "Authorization: NTLM <cut>[\r][\n]"
DEBUG - 2015-07-06 14:59:56,486 - org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
DEBUG - 2015-07-06 14:59:56,564 - org.apache.http.wire - http-outgoing-0 << "end of stream"
DEBUG - 2015-07-06 14:59:56,565 - org.apache.http.wire - http-outgoing-0 >> "b[\r][\n]"
DEBUG - 2015-07-06 14:59:56,565 - org.apache.http.wire - http-outgoing-0 >> "ala ma kota[\r][\n]"
DEBUG - 2015-07-06 14:59:56,565 - org.apache.http.wire - http-outgoing-0 >> "0[\r][\n]"
DEBUG - 2015-07-06 14:59:56,565 - org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
DEBUG - 2015-07-06 14:59:56,565 - org.apache.http.wire - http-outgoing-0 << "end of stream"
DEBUG - 2015-07-06 14:59:56,565 - org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-0: Close connection
DEBUG - 2015-07-06 14:59:56,566 - org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-0: Shutdown connection
DEBUG - 2015-07-06 14:59:56,566 - org.apache.http.impl.execchain.MainClientExec - Connection discarded
DEBUG - 2015-07-06 14:59:56,566 - org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-0: Close connection
DEBUG - 2015-07-06 14:59:56,566 - org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {}->http://kauab-we3.collaboration.example.com:80][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
DEBUG - 2015-07-06 14:59:56,568 - org.apache.http.impl.execchain.MainClientExec - Cancelling request execution
INFO - 2015-07-06 14:59:56,571 - org.springframework.context.annotation.AnnotationConfigApplicationContext - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@68f1b17f: startup date [Mon Jul 06 14:59:54 CEST 2015]; root of context hierarchy
DEBUG - 2015-07-06 14:59:56,572 - org.apache.http.impl.conn.PoolingClientConnectionManager - Connection manager is shutting down
DEBUG - 2015-07-06 14:59:56,572 - org.apache.http.impl.conn.PoolingClientConnectionManager - Connection manager shut down
```

**Comment by lookfirst** [comment]
Hey, thanks for using Sardine. Could this be your issue? https://github.com/lookfirst/sardine/wiki/UsageGuide#preemptive-authentication

**Comment by chudzikp** [comment]
Still not working with: sardine.enablePreemptiveAuthentication("kauab-we3.collaboration.example.com");
it doesn't surprise me because of:
> Only the Basic scheme is supported and a authentication failure is thrown when the server requests a different authentication scheme such as Digest. To disable the use from subsequent requests, use Sardine.disablePreemptiveAuthentication.

Sharepoint uses NTLM for authorization not basic.

**Comment by lookfirst** [comment]
Basically, you're going to have to figure out auth on your own, sorry!  I don't have a Sharepoint server to test against, nor the motivation to figure it out.

The thing to google around for is figuring out how to get HttpClient to do auth against a Sharepoint server and then implement that on top of Sardine.

If you figure it out and want to document it for others benefit (submit a PR for the wiki documentation), that would be great too.

I'm going to close this issue for now as it isn't directly tied to Sardine. If you'd like to keep the discussion going, that is fine as well.

**Comment by chudzikp** [comment]
Ok I now why it's failing (sorry for delay, but wanted I to investigate this a little bit further).
Sorry I don't have time to create PR to fix it right now (and I'm not sure you might want one ;))

Long story:
There is method:
com.github.sardine.impl.SardineImpl#put(java.lang.String, java.io.InputStream, java.lang.String, boolean, long)
And there you create InputStreamEntity from user input stream.
Now when using ntlm (not sure if it's ntlm or sharepoint thing) authentication first request is always rejected with status code 401. Next request will be attempted but since InputStreamEntity is not repetable org.apache.http.entity.InputStreamEntity#isRepeatable it will be impossible to stream bytes again. HttpClient will throw exception because another request attempt was made but request entity can not be processed more then one time.
Method com.github.sardine.Sardine#put(java.lang.String, java.io.File, java.lang.String) should work out of the box without any issues because it uses org.apache.http.entity.FileEntity which is repeatable.

Solution:
I was able to create ugly workaround for this.
First create repeatable streaming http entity:
```
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import lombok.RequiredArgsConstructor;
import org.apache.commons.io.IOUtils;
import org.apache.http.entity.AbstractHttpEntity;
import org.springframework.web.multipart.MultipartFile;

@RequiredArgsConstructor
class RepetableInputStreamEntity extends AbstractHttpEntity {
	final MultipartFile file;//just example which works for me. You can use whatever you want just make sure your entity is repetable and you can create new instance of input stream on each getContent call.

	@Override
	public boolean isRepeatable() {
		return true;
	}

	@Override
	public long getContentLength() {
		return file.getSize();
	}

	@Override
	public InputStream getContent() throws IOException, UnsupportedOperationException {
		return file.getInputStream();
	}

	@Override
	public void writeTo(OutputStream outstream) throws IOException {
		try (InputStream content = getContent()) {
			IOUtils.copy(content, outstream);
		}
	}

	@Override
	public boolean isStreaming() {
		return true;
	}
}
```

Next make sure you are using SardineImpl not Sardine interface:
```
	private static final boolean NO_CONTINUE = false;
	private final SardineImpl sardine;

	public void uploadFile(UploadFileRequest uploadFileRequest) {
		sardine.put(
				uploadFileRequest.getFullFileUrl(),
				uploadFileRequest.getHttpEntity(),
				uploadFileRequest.getContentType(),
				NO_CONTINUE);
	}
```

and you are basically good to go just create SardineImpl using any cosntructor from class SardineImpl.

Only downside is that I'm forced to use SardineImpl.

**Comment by lookfirst** [comment]
:+1: glad you figured it out. =)
