### ISSUE TITLE
connection to https location fails

### ISSUE THREAD

**Issue by lkatamba** [lookfirst/sardine#244]
I am trying to connect to https webdav location, using the below script  
Sardine sardine = SardineFactory.begin("username", "password");
        List<DavResource> resources = sardine.list("https://uri/");
        resources.stream().forEach((res) -> {
            System.out.println(res); // calls the .toString() method.
        });

each time i get this error:

Exception in thread "main" java.net.SocketException: Connection reset
    at java.net.SocketInputStream.read(SocketInputStream.java:209)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
    at sun.security.ssl.InputRecord.read(InputRecord.java:503)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:961)
    at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:918)
    at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
    at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
    at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
    at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
    at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
    at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:214)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160)
    at com.github.sardine.impl.SardineImpl.execute(SardineImpl.java:1008)
    at com.github.sardine.impl.SardineImpl.propfind(SardineImpl.java:446)
    at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:395)
    at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:385)
    at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:379)

**Comment by lookfirst** [comment]
1. Debug or trace level logging.
2. Looks like a connection reset, what is in the server logs?

**Comment by lkatamba** [comment]
I have included Sardine library jar file to my program.

The debug is shown below:
Exception in thread "main" java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:961)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:918)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:214)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160)
	at com.github.sardine.impl.SardineImpl.execute(SardineImpl.java:1008)
	at com.github.sardine.impl.SardineImpl.propfind(SardineImpl.java:446)
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:395)
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:385)
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:379)
	at com.WebDAVRunner.main(WebDAVRunner.java:28)
Java Result: 1
BUILD SUCCESSFUL (total time: 3 seconds)

**Comment by lkatamba** [comment]
I am trying to connect to remote server with commercial Symantec Server certificates

**Comment by lookfirst** [comment]
Please answer the questions above.

**Comment by lkatamba** [comment]
1. Debug or trace level logging.
    That is debug
2. Looks like a connection reset, what is in the server logs?
     I am not using the normal JSE java so no server log

**Comment by lkatamba** [comment]
package com;

import com.github.sardine.DavResource;
import com.github.sardine.Sardine;
import com.github.sardine.SardineFactory;
import java.util.List;

/**
 *
 * @author leonard.katamba
 */
public class WebDAVRunner {

    public static void main(String[] args) throws Exception {
        // Logger logger = LoggerFactory.getLogger(WebDAVRunner.class);
        // WebDAVClient client1 = new WebDAVClient("https://172.20.1.8/testDeposita", 443, "testDeposita", "testSTD@citi!");
        //"deposita", "STD@citi!"
        // client1.checkin("https://172.20.1.8/testDeposita/");            
        //client1.readResources();
        // client1.downloadFile("https://172.20.1.8/deposita/upload/*.txt", "D:/RUCO/", "*.txt");
        //client1.listFolder("https://172.20.1.8/testDeposita/upload/");


        Sardine sardine = SardineFactory.begin("username", "password");
        List<DavResource> resources = sardine.list("https://apps.postalbank.co.tz/testDeposita/upload");
        resources.stream().forEach((res) -> {
            System.out.println(res); // calls the .toString() method.
        });

    }

}

**Comment by lookfirst** [comment]
That isn't debug, that is a stack trace. Turn on debug LOGGING.

You may need to look at the log on apps.postalbank.co.tz (the server you're connecting to) to find out what isn't working.

**Comment by lkatamba** [comment]
This is the server error
Log Name:      System
Source:        NETLOGON
Date:          3/3/2016 12:14:08 PM
Event ID:      5774
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      MKPSD3G1B5J.apps.postalbank.co.tz
Description:
The dynamic registration of the DNS record '_ldap._tcp.apps.postalbank.co.tz. 600 IN SRV 0 100 389 MKPSD3G1B5J.apps.postalbank.co.tz.' failed on the following DNS server:  

DNS server IP address: :: 
Returned Response Code (RCODE): 0 
Returned Status Code: 0  

For computers and users to locate this domain controller, this record must be registered in DNS.  

USER ACTION  
Determine what might have caused this failure, resolve the problem, and initiate registration of the DNS records by the domain controller. To determine what might have caused this failure, run DCDiag.exe. To learn more about DCDiag.exe, see Help and Support Center. To initiate registration of the DNS records by this domain  controller, run 'nltest.exe /dsregdns' from the command prompt on the domain controller or restart Net Logon service. 
  Or, you can manually add this record to DNS, but it is not recommended.  

ADDITIONAL DATA 
Error Value: DNS operation refused.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="NETLOGON" />
    <EventID Qualifiers="0">5774</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-03-03T09:14:08.000Z" />
    <EventRecordID>381469</EventRecordID>
    <Channel>System</Channel>
    <Computer>MKPSD3G1B5J.apps.postalbank.co.tz</Computer>
    <Security />
  </System>
  <EventData>
    <Data>_ldap._tcp.apps.postalbank.co.tz. 600 IN SRV 0 100 389 MKPSD3G1B5J.apps.postalbank.co.tz.</Data>
    <Data>%%9005</Data>
    <Data>::</Data>
    <Data>0</Data>
    <Data>0</Data>
    <Binary>0000</Binary>
  </EventData>
</Event>

**Comment by lookfirst** [comment]
I have no idea, I'm sorry. You're just not providing us with enough information to help you in any way. I've repeatedly asked you for debug logs and server logs and you aren't making that available. Without that information we can't help you. Good luck.

**Comment by lkatamba** [comment]
I am still new in JAVA  as a whole. can you assist how to set that debug logs?

**Comment by kool79** [comment]
v5.9 successfully connects to https
So can be closed

**Comment by lookfirst** [comment]
@kool79 thanks!
