### ISSUE TITLE
cannot lock existing directories

### ISSUE THREAD

**Issue by abstratt** [lookfirst/sardine#250]
If I try to lock and unlock an existing directory, the lock operation seems to work, but the unlock operation fails.

**Comment by abstratt** [comment]
Test addition for LockTest.java:
```
	@Test
    public void testLockUnlockDir() throws Exception
    {
        String base = System.getProperty("test.webdav.base", "http://test.cyberduck.ch/dav/anon/sardine/");
        String username = System.getProperty("test.webdav.username", null);
        String password = System.getProperty("test.webdav.password", null);
        Sardine sardine = SardineFactory.begin(username, password);
        String url = base + UUID.randomUUID().toString();
        sardine.createDirectory(url);
        try
        {
            String token = sardine.lock(url);
            sardine.put(url + "/file.txt", "Some contents".getBytes());
            try
            {
                sardine.delete(url);
                fail("Expected delete to fail on locked resource");
            }
            catch (SardineException e)
            {
                assertEquals(423, e.getStatusCode());
            }
            sardine.unlock(url, token);
        }
        finally
        {
           sardine.delete(url);
        }
    }
```

**Comment by abstratt** [comment]
The test above fails when trying to add a file to a locked dir:

```
com.github.sardine.impl.SardineException: Unexpected response (423 Locked)
	at com.github.sardine.impl.handler.ValidatingResponseHandler.validateResponse(ValidatingResponseHandler.java:48)
	at com.github.sardine.impl.handler.VoidResponseHandler.handleResponse(VoidResponseHandler.java:34)
	at com.github.sardine.impl.handler.VoidResponseHandler.handleResponse(VoidResponseHandler.java:1)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
	at com.github.sardine.impl.SardineImpl.execute(SardineImpl.java:1036)
	at com.github.sardine.impl.SardineImpl.execute(SardineImpl.java:1003)
	at com.github.sardine.impl.SardineImpl.delete(SardineImpl.java:949)
	at com.github.sardine.LockTest.testLockUnlockDir(LockTest.java:84)
```

**Comment by abstratt** [comment]
Actually, the stacktrace above is a secondary exception that happens on clean-up. This is the original exception:

```
com.github.sardine.impl.SardineException: Unexpected response (423 Locked)
	at com.github.sardine.impl.handler.ValidatingResponseHandler.validateResponse(ValidatingResponseHandler.java:48)
	at com.github.sardine.impl.handler.VoidResponseHandler.handleResponse(VoidResponseHandler.java:34)
	at com.github.sardine.impl.handler.VoidResponseHandler.handleResponse(VoidResponseHandler.java:1)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
	at com.github.sardine.impl.SardineImpl.execute(SardineImpl.java:1036)
	at com.github.sardine.impl.SardineImpl.execute(SardineImpl.java:1003)
	at com.github.sardine.impl.SardineImpl.put(SardineImpl.java:914)
	at com.github.sardine.impl.SardineImpl.put(SardineImpl.java:897)
	at com.github.sardine.impl.SardineImpl.put(SardineImpl.java:885)
	at com.github.sardine.impl.SardineImpl.put(SardineImpl.java:819)
	at com.github.sardine.impl.SardineImpl.put(SardineImpl.java:812)
	at com.github.sardine.LockTest.testLockUnlockDir(LockTest.java:70)
```

**Comment by dkocher** [comment]
See also #248.

**Comment by Ichicon** [comment]
Hey it's an old thread but I just had to do the same thing and I found out how by reading some of the webdav RFCs :

For the put method you can do it by adding a If Http header  like this :
```
Map<String, String> headers = new HashMap<>(); 
// fileName is the name of the file at the end of the url
// lockToken has been retrieved when using the lock function
headers.put(HttpHeaders.IF, "<" + fileName + "> (<" + lockToken + ">)");
sardine.put(url, inputStream,  headers);
```

For the patch method, you'll have to modify the lib to add custom header and do the same thing as put is doing (but with HttpPropPatch instead of HttpPut).

**Comment by lookfirst** [comment]
@Ichicon Thanks for the information. =)
