### ISSUE TITLE
Got exception NoSuchMethodError setValidateAfterInactivity when deploy to tomcat 8

### ISSUE THREAD

**Issue by cwichoski** [lookfirst/sardine#252]
Hi,

I just got the Sardine verison 5.7 from Maven Repository, integrated with some JAX-RS service and on follow line:

`Sardine sardine = SardineFactory.begin(DAV_USER,DAV_PASSWORD);`

got this exception:
`
ContainerException: java.lang.NoSuchMethodError: org.apache.http.impl.conn.CPool.setValidateAfterInactivity(I)V] with root cause
 java.lang.NoSuchMethodError: org.apache.http.impl.conn.CPool.setValidateAfterInactivity(I)V
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:176)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:149)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:125)
	at com.github.sardine.impl.SardineImpl.createDefaultConnectionManager(SardineImpl.java:1127)
	at com.github.sardine.impl.SardineImpl.configure(SardineImpl.java:1065)
	at com.github.sardine.impl.SardineImpl.<init>(SardineImpl.java:203)
	at com.github.sardine.SardineFactory.begin(SardineFactory.java:44)
	at com.github.sardine.SardineFactory.begin(SardineFactory.java:34)
`

I know that appears to be some problem between dependencies, anyone know how to solve that? Maybe a problem with conflict dependencies of Jersey? Tomcat?

**Comment by lookfirst** [comment]
This isn't a sardine issue, it is a classpath issue. Sounds like you have another http client jar in your classpath. =)

**Comment by cwichoski** [comment]
Yes, on Maven I'm integrating with WSO2 Identity Server that have same dependencies that Sardine have, but a old one.

**Comment by lookfirst** [comment]
Yup, you'll need classpath isolation of some sort to make things work properly...
