### ISSUE TITLE
Please compatible with jdk1.7 and jdk1.8.

### ISSUE THREAD

**Issue by dylan-tao** [lookfirst/sardine#292]
ps:
`com.github.sardine.impl.SardineException: Unexpected response (500 Internal Server Error)
	at com.github.sardine.impl.handler.ValidatingResponseHandler.validateResponse(ValidatingResponseHandler.java:48)
	at com.github.sardine.impl.handler.VoidResponseHandler.handleResponse(VoidResponseHandler.java:34)
	at com.github.sardine.impl.handler.VoidResponseHandler.handleResponse(VoidResponseHandler.java:29)`

**Comment by lookfirst** [comment]
The stack trace doesn't relate to the title of the issue. 500 server error doesn't seem like compatibility with jdk1.7/8. Can you please expand on what's going on here? Thanks.

**Comment by dylan-tao** [comment]
I think Sardine cannot run stably on jdk1.8，internal reporting is wrong. Can you test it?

**Comment by decowboy** [comment]
No issues on jdk1.8 for me.

**Comment by dylan-tao** [comment]
thanks~

**Comment by lookfirst** [comment]
I don't think there is an issue here anymore, closing. Please reopen if you think you need this still. =)
