### ISSUE TITLE
Working on implementation as a module for a voip-pbx

### ISSUE THREAD

**Issue by Fabian95qw** [lookfirst/sardine#295]
Good day everybody.

I'm developing so called "modules" for the voip-pbx called Starface. It's running on a Java-application in catalina (tomcat), on top of a normal asterisk.

It has a classloader Interface, which allows everybody to write additional functions, or load additional libraries into the System.

I've sucessfully developed a module, to import Exchange contacts, Google contacts, or import simple .csv files into the addressbook.

I'm currently trying to implement carddav as possible sources for the adressbook. But we've run into issues, when running the following Code:

`		
		
		log.debug("Starting CardDAV Import");
		
		Map<EPerson, Integer> Template = null; //Template for later Conversion of the VCard

		Template = TemplateProvider.GetCardDavTemplate(log);	
		
		log.debug("Trying to Authenticate: " + Username);
		Sardine S = SardineFactory.begin(Username, Password);
		log.debug("Trying to get URL: "+ TargetURL);
		List<DavResource> Resources = S.list(TargetURL);
		
		List<String> DAVPaths = new ArrayList<String>();
		
		log.debug("Collected: " + Resources.size()+" DAVResources");
		
		for(DavResource DR : Resources)
		{
			if(DR.getContentType().contains("text/vcard"))
			{
				DAVPaths.add(DR.getPath());
			}
		}
		
		log.debug("Total VCards in Resoruces:" + DAVPaths.size());
		
		VCard VC = null;
		
		List<VCard> VCards = new ArrayList<VCard>();
		log.debug("Converting VCards");
		for(String Path : DAVPaths)
		{
			VC = DavPathtoVCard(Path, S, log);
			if(VC==null)
			{
				continue;
			}
			else
			{
				VCards.add(VC);
			}
		}
		
		log.debug("Total Valid VCards:" + VCards.size());
		//More Code, but no longer relevant
`

I can execute this code locally without any problems. But once imported on the pbx, it will throw a stacktrace:
`
Root cause:  
com.github.sardine.impl.SardineException: Unexpected response (400 Bad Request)
	at com.github.sardine.impl.handler.ValidatingResponseHandler.validateResponse(ValidatingResponseHandler.java:48)
	at com.github.sardine.impl.handler.MultiStatusResponseHandler.handleResponse(MultiStatusResponseHandler.java:40)
	at com.github.sardine.impl.handler.MultiStatusResponseHandler.handleResponse(MultiStatusResponseHandler.java:35)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
	at com.github.sardine.impl.SardineImpl.execute(SardineImpl.java:1043)
	at com.github.sardine.impl.SardineImpl.execute(SardineImpl.java:1012)
	at com.github.sardine.impl.SardineImpl.propfind(SardineImpl.java:455)
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:404)
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:394)
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:388)
	at nucom.module.contacts.importer.v2.imports.carddav.CardDAVImporter.execute(CardDAVImporter.java:84)
//Stacktrace no longer relevant
`
Line 83 is: 

`
Sardine S = SardineFactory.begin(Username, Password);
`

I think it's a dependency issue. The starface already provides a lot of libraries, of which some are outdated. But the classloader won't load newer libararies, if there is already a loaded class with a different version.

So i tried using the Sardine SourceCode, and compile it directly with all the libraries supplied with the pbx. I had to add vinnie-2.0.2, in order to sucessfully compile it, all other libraries seem to exist on the pbx in some form already.

Using the newly compiled version of Sardine, i run into this error:

`
java.lang.NoClassDefFoundError: com/github/sardine/model/Read
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at com.sun.xml.internal.bind.v2.model.nav.ReflectionNavigator.getDeclaredMethods(ReflectionNavigator.java:280)
	at com.sun.xml.internal.bind.v2.model.nav.ReflectionNavigator.getDeclaredMethods(ReflectionNavigator.java:47)
	at com.sun.xml.internal.bind.v2.model.impl.RegistryInfoImpl.<init>(RegistryInfoImpl.java:81)
	at com.sun.xml.internal.bind.v2.model.impl.ModelBuilder.addRegistry(ModelBuilder.java:402)
	at com.sun.xml.internal.bind.v2.model.impl.ModelBuilder.getTypeInfo(ModelBuilder.java:372)
	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:439)
	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:277)
	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:124)
	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1123)
	at com.sun.xml.internal.bind.v2.ContextFactory.createContext(ContextFactory.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:247)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:234)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:462)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:641)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:584)
	at com.github.sardine.util.SardineUtil.<clinit>(SardineUtil.java:88)
	at com.github.sardine.impl.SardineImpl.propfind(SardineImpl.java:459)
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:409)
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:399)
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:393)
	at nucom.module.contacts.importer.v2.imports.carddav.CardDAVImporter.execute(CardDAVImporter.java:82)
`

The JAXBContext does run in some kind of error.

I'm currently trying to resolve this error, but i don't know why it can't find the Read.class, when it's clearly there and loaded.

Maybe somebody has an idea, how i can resolve this.

Sincerely Fabian95qw

**Comment by Fabian95qw** [comment]
The issue was never resolved. I made a standalone runnable, which i invoked, that way it worked.
